package com.hippo.ehviewer.dao;

import org.greenrobot.greendao.annotation.*;
import android.os.Parcel;
import com.hippo.ehviewer.client.data.GalleryInfo;
import com.hippo.ehviewer.util.JsonUtils;
import org.json.JSONObject;
import java.util.ArrayList;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DOWNLOADS".
 */
@Entity(nameInDb = "DOWNLOADS")
public class DownloadInfo extends GalleryInfo {

	public int state;
	public int legacy;
	public long time;
	public String label;
	public String archiveUri; // URI for imported archive files
	public static final Creator<DownloadInfo> CREATOR = new Creator<DownloadInfo>() {
		@Override
		public DownloadInfo createFromParcel(Parcel source) {
			return new DownloadInfo(source);
		}

		@Override
		public DownloadInfo[] newArray(int size) {
			return new DownloadInfo[size];
		}
	};
	public static final int STATE_INVALID = -1;
	public static final int STATE_NONE = 0;
	public static final int STATE_WAIT = 1;
	public static final int STATE_DOWNLOAD = 2;
	public static final int STATE_FINISH = 3;
	public static final int STATE_FAILED = 4;
	public static final int STATE_UPDATE = 5;
	public static final int GOTO_NEW = 6;
	public long speed;
	public long remaining;
	public int finished;
	public int downloaded;
	public int total;
	public long fileSize = -1; // 文件夹总大小（字节），-1表示未计算


	@Generated
	public DownloadInfo() {
	}

	public DownloadInfo(long gid) {
		this.gid = gid;
	}

	@Generated
	public DownloadInfo(long gid, String token, String title, String titleJpn, String thumb, int category,
			String posted, String uploader, float rating, String simpleLanguage, int state, int legacy, long time,
			String label, String archiveUri) {
		this.gid = gid;
		this.token = token;
		this.title = title;
		this.titleJpn = titleJpn;
		this.thumb = thumb;
		this.category = category;
		this.posted = posted;
		this.uploader = uploader;
		this.rating = rating;
		this.simpleLanguage = simpleLanguage;
		this.state = state;
		this.legacy = legacy;
		this.time = time;
		this.label = label;
		this.archiveUri = archiveUri;
	}

	public long getGid() {
		return gid;
	}

	public void setGid(long gid) {
		this.gid = gid;
	}

	public String getToken() {
		return token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getTitleJpn() {
		return titleJpn;
	}

	public void setTitleJpn(String titleJpn) {
		this.titleJpn = titleJpn;
	}

	public String getThumb() {
		return thumb;
	}

	public void setThumb(String thumb) {
		this.thumb = thumb;
	}

	public int getCategory() {
		return category;
	}

	public void setCategory(int category) {
		this.category = category;
	}

	public String getPosted() {
		return posted;
	}

	public void setPosted(String posted) {
		this.posted = posted;
	}

	public String getUploader() {
		return uploader;
	}

	public void setUploader(String uploader) {
		this.uploader = uploader;
	}

	public float getRating() {
		return rating;
	}

	public void setRating(float rating) {
		this.rating = rating;
	}

	public String getSimpleLanguage() {
		return simpleLanguage;
	}

	public void setSimpleLanguage(String simpleLanguage) {
		this.simpleLanguage = simpleLanguage;
	}

	public int getState() {
		return state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public int getLegacy() {
		return legacy;
	}

	public void setLegacy(int legacy) {
		this.legacy = legacy;
	}

	public long getTime() {
		return time;
	}

	public void setTime(long time) {
		this.time = time;
	}

	public String getLabel() {
		return label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getArchiveUri() {
		return archiveUri;
	}

	public void setArchiveUri(String archiveUri) {
		this.archiveUri = archiveUri;
	}

	@Override
	public int describeContents() {
		return 0;
	}

	@Override
	public void writeToParcel(Parcel dest, int flags) {
		super.writeToParcel(dest, flags);
		dest.writeInt(this.state);
		dest.writeInt(this.legacy);
		dest.writeLong(this.time);
		dest.writeString(this.label);
		dest.writeString(this.archiveUri);
	}

	protected DownloadInfo(Parcel in) {
		super(in);
		this.state = in.readInt();
		this.legacy = in.readInt();
		this.time = in.readLong();
		this.label = in.readString();
		this.archiveUri = in.readString();
	}

	public DownloadInfo(GalleryInfo galleryInfo) {
		this.gid = galleryInfo.gid;
		this.token = galleryInfo.token;
		this.title = galleryInfo.title;
		this.titleJpn = galleryInfo.titleJpn;
		this.thumb = galleryInfo.thumb;
		this.category = galleryInfo.category;
		this.posted = galleryInfo.posted;
		this.uploader = galleryInfo.uploader;
		this.rating = galleryInfo.rating;
		this.simpleTags = galleryInfo.simpleTags;
		this.simpleLanguage = galleryInfo.simpleLanguage;
	}

	public void updateInfo(GalleryInfo galleryInfo) {
		this.token = galleryInfo.token;
		this.title = galleryInfo.title;
		this.titleJpn = galleryInfo.titleJpn;
		this.thumb = galleryInfo.thumb;
		this.category = galleryInfo.category;
		this.posted = galleryInfo.posted;
		this.uploader = galleryInfo.uploader;
		this.rating = galleryInfo.rating;
		this.simpleTags = galleryInfo.simpleTags;
		this.simpleLanguage = galleryInfo.simpleLanguage;
	}

	public JSONObject toJson() {
		JSONObject jsonObject = super.toJson();
		JsonUtils.put(jsonObject, "finished", finished);
		JsonUtils.put(jsonObject, "legacy", legacy);
		JsonUtils.put(jsonObject, "label", label);
		JsonUtils.put(jsonObject, "downloaded", downloaded);
		JsonUtils.put(jsonObject, "remaining", remaining);
		JsonUtils.put(jsonObject, "speed", speed);
		JsonUtils.put(jsonObject, "state", state);
		JsonUtils.put(jsonObject, "time", time);
		JsonUtils.put(jsonObject, "total", total);
		JsonUtils.put(jsonObject, "archiveUri", archiveUri);
		return jsonObject;
	}

	public static DownloadInfo downloadInfoFromJson(JSONObject object) throws ClassCastException {
		DownloadInfo downloadInfo = GalleryInfo.galleryInfoFromJson(object).getDownloadInfo(null);
		downloadInfo.finished = object.optInt("finished");
		downloadInfo.legacy = object.optInt("legacy");
		downloadInfo.label = JsonUtils.optStringOrNull(object, "label");
		downloadInfo.downloaded = object.optInt("downloaded");
		downloadInfo.remaining = object.optLong("remaining");
		downloadInfo.speed = object.optLong("speed");
		downloadInfo.state = object.optInt("state");
		downloadInfo.time = object.optLong("time");
		downloadInfo.total = object.optInt("total");
		downloadInfo.archiveUri = JsonUtils.optStringOrNull(object, "archiveUri");
		return downloadInfo;
	}

}
